---
abstract: 'Check for the presence of a compiler'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Cwd: '0'
  File::Path: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-HasCompiler
provides:
  ExtUtils::HasCompiler:
    file: lib/ExtUtils/HasCompiler.pm
    version: '0.023'
requires:
  Carp: '0'
  DynaLoader: '0'
  Exporter: '0'
  ExtUtils::Mksymlists: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-HasCompiler
  repository: git://github.com/Leont/extutils-hascompiler.git
version: '0.023'
x_contributors:
  - 'bulk88 <bulk88@hotmail.com>'
  - 'Craig A. Berry <craigberry@mac.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Håkon Hægland <hakon.hagland@gmail.com>'
  - 'Leon Timmermans <fawaka@gmail.com>'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
